### ISSUE TITLE
Scrollbar showing in Panel

### ISSUE THREAD

**Issue by bassmartin** [JarekToro/responsive-layout#16]
There is a scrollbar showing in the Panel with the following code:

```
ResponsiveLayout layout = new ResponsiveLayout(ResponsiveLayout.ContainerType.FLUID)
        setCompositionRoot(layout) // 'this', is a Vaadin Panel
        layout.with {
            addRow().withMargin(ResponsiveRow.MarginSize.SMALL, true).withVerticalSpacing(ResponsiveRow.SpacingSize.SMALL, true).withHorizontalSpacing(true).with {
                addColumn().withDisplayRules(12, 12,12,12).setComponent(new Label("Test"))
            }
        }
```

<img width="744" alt="screen shot 2016-11-01 at 09 18 20" src="https://cloud.githubusercontent.com/assets/10145772/19890969/2e1a8f04-a014-11e6-9c60-4f1224288af3.png">

I did some testing, and it seems to be caused by the usage of both ```withMargin(ResponsiveRow.MarginSize.SMALL, true).withVerticalSpacing(ResponsiveRow.SpacingSize.SMALL, true)```

Thanks.

**Comment by JarekToro** [comment]
Ran into a similar issue while working on issue #14.
It is fixed and will be committed soon.

**Comment by bassmartin** [comment]
I still have the issue @JarekToro 
If I set the ```SpacingSize.NORMAL```, the scrollbar does not show.

Thanks.

**Comment by JarekToro** [comment]
Cant seem to recreate the issue? What browser are you using?


This is code I'm recreating with
```java
 Panel panel = new Panel("Panel");
        setContent(panel);
        ResponsiveLayout layout = new ResponsiveLayout(ResponsiveLayout.ContainerType.FLUID);

        panel.setContent(layout);

        layout.addRow().withMargin(ResponsiveRow.MarginSize.SMALL)
                .withVerticalSpacing(ResponsiveRow.SpacingSize.SMALL, true)
                .withHorizontalSpacing(true)
                .addColumn().withDisplayRules(12, 12, 12, 12).setComponent(new Label("Test"));

```

**Comment by bassmartin** [comment]
Safari. I'll try with Chrome tomorrow.

--
Sébastien Martin

**Comment by bassmartin** [comment]
I just retested on both browser and no scrollbar is showing. I guess I was using a cached CSS in my browser when I reopened the issue.

Sorry about that.

You can close the issue :p

Left is safari, right is chrome:

<img width="1604" alt="screen shot 2016-11-30 at 10 31 55" src="https://cloud.githubusercontent.com/assets/10145772/20758628/68de84e8-b6e8-11e6-8d31-655fb6ba8982.png">

**Comment by JarekToro** [comment]
No problem. Glad it's fixed
